"""
MMSI Maritime Identification Digit (MID) → country + flag emoji.

The first three digits of an MMSI identify the vessel's flag state.
Source: ITU Table of Maritime Identification Digits.
"""

from __future__ import annotations

# MID -> (country name, flag emoji)
_MID_TABLE: dict[str, tuple[str, str]] = {
    "201": ("Albania", "🇦🇱"),
    "202": ("Andorra", "🇦🇩"),
    "203": ("Austria", "🇦🇹"),
    "204": ("Azores (Portugal)", "🇵🇹"),
    "205": ("Belgium", "🇧🇪"),
    "206": ("Belarus", "🇧🇾"),
    "207": ("Bulgaria", "🇧🇬"),
    "208": ("Vatican City", "🇻🇦"),
    "209": ("Cyprus", "🇨🇾"),
    "210": ("Cyprus", "🇨🇾"),
    "211": ("Germany", "🇩🇪"),
    "212": ("Cyprus", "🇨🇾"),
    "213": ("Georgia", "🇬🇪"),
    "214": ("Moldova", "🇲🇩"),
    "215": ("Malta", "🇲🇹"),
    "216": ("Armenia", "🇦🇲"),
    "218": ("Germany", "🇩🇪"),
    "219": ("Denmark", "🇩🇰"),
    "220": ("Denmark", "🇩🇰"),
    "224": ("Spain", "🇪🇸"),
    "225": ("Spain", "🇪🇸"),
    "226": ("France", "🇫🇷"),
    "227": ("France", "🇫🇷"),
    "228": ("France", "🇫🇷"),
    "229": ("Malta", "🇲🇹"),
    "230": ("Finland", "🇫🇮"),
    "231": ("Faroe Islands", "🇫🇴"),
    "232": ("United Kingdom", "🇬🇧"),
    "233": ("United Kingdom", "🇬🇧"),
    "234": ("United Kingdom", "🇬🇧"),
    "235": ("United Kingdom", "🇬🇧"),
    "236": ("Gibraltar", "🇬🇮"),
    "237": ("Greece", "🇬🇷"),
    "238": ("Croatia", "🇭🇷"),
    "239": ("Greece", "🇬🇷"),
    "240": ("Greece", "🇬🇷"),
    "241": ("Greece", "🇬🇷"),
    "242": ("Morocco", "🇲🇦"),
    "243": ("Hungary", "🇭🇺"),
    "244": ("Netherlands", "🇳🇱"),
    "245": ("Netherlands", "🇳🇱"),
    "246": ("Netherlands", "🇳🇱"),
    "247": ("Italy", "🇮🇹"),
    "248": ("Malta", "🇲🇹"),
    "249": ("Malta", "🇲🇹"),
    "250": ("Ireland", "🇮🇪"),
    "251": ("Iceland", "🇮🇸"),
    "252": ("Liechtenstein", "🇱🇮"),
    "253": ("Luxembourg", "🇱🇺"),
    "254": ("Monaco", "🇲🇨"),
    "255": ("Madeira (Portugal)", "🇵🇹"),
    "256": ("Malta", "🇲🇹"),
    "257": ("Norway", "🇳🇴"),
    "258": ("Norway", "🇳🇴"),
    "259": ("Norway", "🇳🇴"),
    "261": ("Poland", "🇵🇱"),
    "262": ("Montenegro", "🇲🇪"),
    "263": ("Portugal", "🇵🇹"),
    "264": ("Romania", "🇷🇴"),
    "265": ("Sweden", "🇸🇪"),
    "266": ("Sweden", "🇸🇪"),
    "267": ("Slovakia", "🇸🇰"),
    "268": ("San Marino", "🇸🇲"),
    "269": ("Switzerland", "🇨🇭"),
    "270": ("Czech Republic", "🇨🇿"),
    "271": ("Turkey", "🇹🇷"),
    "272": ("Ukraine", "🇺🇦"),
    "273": ("Russia", "🇷🇺"),
    "274": ("North Macedonia", "🇲🇰"),
    "275": ("Latvia", "🇱🇻"),
    "276": ("Estonia", "🇪🇪"),
    "277": ("Lithuania", "🇱🇹"),
    "278": ("Slovenia", "🇸🇮"),
    "279": ("Serbia", "🇷🇸"),
    "301": ("Anguilla", "🇦🇮"),
    "303": ("Alaska (USA)", "🇺🇸"),
    "304": ("Antigua and Barbuda", "🇦🇬"),
    "305": ("Antigua and Barbuda", "🇦🇬"),
    "306": ("Netherlands Antilles", "🇳🇱"),
    "307": ("Aruba", "🇦🇼"),
    "308": ("Bahamas", "🇧🇸"),
    "309": ("Bahamas", "🇧🇸"),
    "310": ("Bermuda", "🇧🇲"),
    "311": ("Bahamas", "🇧🇸"),
    "316": ("Canada", "🇨🇦"),
    "319": ("Cayman Islands", "🇰🇾"),
    "338": ("USA", "🇺🇸"),
    "339": ("Cuba", "🇨🇺"),
    "351": ("Panama", "🇵🇦"),
    "352": ("Panama", "🇵🇦"),
    "353": ("Panama", "🇵🇦"),
    "354": ("Panama", "🇵🇦"),
    "355": ("Panama", "🇵🇦"),
    "356": ("Panama", "🇵🇦"),
    "357": ("Panama", "🇵🇦"),
    "370": ("Panama", "🇵🇦"),
    "371": ("Panama", "🇵🇦"),
    "372": ("Panama", "🇵🇦"),
    "373": ("Panama", "🇵🇦"),
    "374": ("Panama", "🇵🇦"),
    "401": ("Afghanistan", "🇦🇫"),
    "403": ("Saudi Arabia", "🇸🇦"),
    "405": ("Bangladesh", "🇧🇩"),
    "408": ("Bahrain", "🇧🇭"),
    "410": ("Bhutan", "🇧🇹"),
    "412": ("China", "🇨🇳"),
    "413": ("China", "🇨🇳"),
    "414": ("China", "🇨🇳"),
    "416": ("Taiwan", "🇹🇼"),
    "417": ("Sri Lanka", "🇱🇰"),
    "419": ("India", "🇮🇳"),
    "422": ("Iran", "🇮🇷"),
    "423": ("Azerbaijan", "🇦🇿"),
    "425": ("Iraq", "🇮🇶"),
    "428": ("Israel", "🇮🇱"),
    "431": ("Japan", "🇯🇵"),
    "432": ("Japan", "🇯🇵"),
    "434": ("Turkmenistan", "🇹🇲"),
    "436": ("Kazakhstan", "🇰🇿"),
    "438": ("Jordan", "🇯🇴"),
    "440": ("South Korea", "🇰🇷"),
    "441": ("South Korea", "🇰🇷"),
    "443": ("Palestine", "🇵🇸"),
    "445": ("North Korea", "🇰🇵"),
    "447": ("Kuwait", "🇰🇼"),
    "450": ("Lebanon", "🇱🇧"),
    "451": ("Kyrgyzstan", "🇰🇬"),
    "453": ("Macao", "🇲🇴"),
    "455": ("Maldives", "🇲🇻"),
    "457": ("Mongolia", "🇲🇳"),
    "459": ("Nepal", "🇳🇵"),
    "461": ("Oman", "🇴🇲"),
    "463": ("Pakistan", "🇵🇰"),
    "466": ("Qatar", "🇶🇦"),
    "468": ("Syria", "🇸🇾"),
    "470": ("UAE", "🇦🇪"),
    "472": ("Uzbekistan", "🇺🇿"),
    "477": ("Hong Kong", "🇭🇰"),
    "478": ("Bosnia and Herzegovina", "🇧🇦"),
    "503": ("Australia", "🇦🇺"),
    "506": ("Myanmar", "🇲🇲"),
    "508": ("Brunei", "🇧🇳"),
    "510": ("Micronesia", "🇫🇲"),
    "511": ("Palau", "🇵🇼"),
    "512": ("New Zealand", "🇳🇿"),
    "514": ("Cambodia", "🇰🇭"),
    "515": ("Cambodia", "🇰🇭"),
    "516": ("Christmas Island", "🇨🇽"),
    "518": ("Cook Islands", "🇨🇰"),
    "520": ("Fiji", "🇫🇯"),
    "523": ("Cocos Islands", "🇨🇨"),
    "525": ("Indonesia", "🇮🇩"),
    "529": ("Kiribati", "🇰🇮"),
    "531": ("Laos", "🇱🇦"),
    "533": ("Malaysia", "🇲🇾"),
    "536": ("Northern Mariana Islands", "🇲🇵"),
    "538": ("Marshall Islands", "🇲🇭"),
    "540": ("New Caledonia", "🇳🇨"),
    "542": ("Niue", "🇳🇺"),
    "544": ("Nauru", "🇳🇷"),
    "546": ("French Polynesia", "🇵🇫"),
    "548": ("Philippines", "🇵🇭"),
    "553": ("Papua New Guinea", "🇵🇬"),
    "555": ("Pitcairn Islands", "🇵🇳"),
    "557": ("Solomon Islands", "🇸🇧"),
    "559": ("Samoa", "🇼🇸"),
    "561": ("Singapore", "🇸🇬"),
    "563": ("Singapore", "🇸🇬"),
    "564": ("Singapore", "🇸🇬"),
    "565": ("Singapore", "🇸🇬"),
    "566": ("Singapore", "🇸🇬"),
    "567": ("Thailand", "🇹🇭"),
    "570": ("Tonga", "🇹🇴"),
    "572": ("Tuvalu", "🇹🇻"),
    "574": ("Vietnam", "🇻🇳"),
    "576": ("Vanuatu", "🇻🇺"),
    "578": ("Wallis and Futuna", "🇼🇫"),
    "601": ("South Africa", "🇿🇦"),
    "603": ("Angola", "🇦🇴"),
    "605": ("Algeria", "🇩🇿"),
    "607": ("Saint Paul Island", "🇫🇷"),
    "608": ("Ascension Island", "🇸🇭"),
    "609": ("Burundi", "🇧🇮"),
    "610": ("Benin", "🇧🇯"),
    "611": ("Botswana", "🇧🇼"),
    "612": ("Central African Republic", "🇨🇫"),
    "613": ("Cameroon", "🇨🇲"),
    "615": ("Congo", "🇨🇬"),
    "616": ("Comoros", "🇰🇲"),
    "617": ("Cape Verde", "🇨🇻"),
    "618": ("Crozet Archipelago", "🇫🇷"),
    "619": ("Ivory Coast", "🇨🇮"),
    "620": ("Djibouti", "🇩🇯"),
    "621": ("Egypt", "🇪🇬"),
    "622": ("Ethiopia", "🇪🇹"),
    "624": ("Eritrea", "🇪🇷"),
    "625": ("Gabon", "🇬🇦"),
    "626": ("Ghana", "🇬🇭"),
    "627": ("Gambia", "🇬🇲"),
    "629": ("Guinea-Bissau", "🇬🇼"),
    "630": ("Equatorial Guinea", "🇬🇶"),
    "631": ("Guinea", "🇬🇳"),
    "632": ("Burkina Faso", "🇧🇫"),
    "633": ("Kenya", "🇰🇪"),
    "634": ("Kerguelen Islands", "🇫🇷"),
    "635": ("Liberia", "🇱🇷"),
    "636": ("Liberia", "🇱🇷"),
    "637": ("Liberia", "🇱🇷"),
    "638": ("Libya", "🇱🇾"),
    "642": ("Libya", "🇱🇾"),
    "644": ("Lesotho", "🇱🇸"),
    "645": ("Mauritius", "🇲🇺"),
    "647": ("Madagascar", "🇲🇬"),
    "649": ("Mali", "🇲🇱"),
    "650": ("Mozambique", "🇲🇿"),
    "654": ("Mauritania", "🇲🇷"),
    "655": ("Malawi", "🇲🇼"),
    "656": ("Niger", "🇳🇪"),
    "657": ("Nigeria", "🇳🇬"),
    "659": ("Namibia", "🇳🇦"),
    "660": ("Reunion", "🇷🇪"),
    "661": ("Rwanda", "🇷🇼"),
    "662": ("Sudan", "🇸🇩"),
    "663": ("Senegal", "🇸🇳"),
    "664": ("Seychelles", "🇸🇨"),
    "665": ("Saint Helena", "🇸🇭"),
    "666": ("Somalia", "🇸🇴"),
    "667": ("Sierra Leone", "🇸🇱"),
    "668": ("São Tomé and Príncipe", "🇸🇹"),
    "669": ("Swaziland", "🇸🇿"),
    "670": ("Chad", "🇹🇩"),
    "671": ("Togo", "🇹🇬"),
    "672": ("Tunisia", "🇹🇳"),
    "674": ("Tanzania", "🇹🇿"),
    "675": ("Uganda", "🇺🇬"),
    "676": ("DR Congo", "🇨🇩"),
    "677": ("Tanzania", "🇹🇿"),
    "678": ("Zambia", "🇿🇲"),
    "679": ("Zimbabwe", "🇿🇼"),
    "701": ("Argentina", "🇦🇷"),
    "710": ("Brazil", "🇧🇷"),
    "720": ("Bolivia", "🇧🇴"),
    "725": ("Chile", "🇨🇱"),
    "730": ("Colombia", "🇨🇴"),
    "735": ("Ecuador", "🇪🇨"),
    "740": ("Falkland Islands", "🇫🇰"),
    "745": ("French Guiana", "🇬🇫"),
    "750": ("Guyana", "🇬🇾"),
    "755": ("Paraguay", "🇵🇾"),
    "760": ("Peru", "🇵🇪"),
    "765": ("Suriname", "🇸🇷"),
    "770": ("Uruguay", "🇺🇾"),
    "775": ("Venezuela", "🇻🇪"),
}


def mid_lookup(mmsi: int) -> tuple[str, str]:
    """
    Return (country_name, flag_emoji) for a given MMSI.
    Falls back to ('Unknown', '🌐') if the MID is not in the table.
    """
    mid = str(mmsi)[:3]
    return _MID_TABLE.get(mid, ("Unknown", "🌐"))
